project_id = "ghhafcmjhmwwfhldmxzc"

[functions.generate-video]
verify_jwt = true

[functions.upload-character-image]
verify_jwt = true

[functions.video-webhook-callback]
verify_jwt = false

[functions.generate-image]
verify_jwt = true

[functions.image-webhook-callback]
verify_jwt = false

[functions.enhance-prompt]
verify_jwt = true
