import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { topic, jobTitle, companyName } = await req.json();

    if (!topic) {
      return new Response(
        JSON.stringify({ error: 'Topic/Details are required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const OPENROUTER_API_KEY = Deno.env.get('OPENROUTER_API_KEY');
    if (!OPENROUTER_API_KEY) {
      throw new Error('OPENROUTER_API_KEY is not configured');
    }

    console.log('Generating cover letter with GPT-4.1...');
    console.log('Topic:', topic);
    console.log('Job Title:', jobTitle);
    console.log('Company Name:', companyName);

    const currentDate = new Date();
    const formattedDate = currentDate.toLocaleDateString('en-US', { 
      month: 'long', 
      day: 'numeric',
      year: 'numeric' 
    });
    
    const systemPrompt = `You are an expert career coach and professional cover letter writer with extensive experience helping candidates land their dream jobs. Generate compelling, personalized cover letters that stand out from the competition.

Your cover letters should follow this structure:
1. Header - Include date (${formattedDate}) and professional salutation
2. Opening Paragraph - Strong hook that captures attention and states the position
3. Body Paragraph 1 - Highlight relevant experience and key accomplishments
4. Body Paragraph 2 - Demonstrate knowledge of the company and cultural fit
5. Body Paragraph 3 - Specific skills and value proposition
6. Closing Paragraph - Clear call to action and enthusiasm
7. Professional Sign-off - Formal closing with signature line

Guidelines:
- Keep the letter to one page (approximately 300-400 words)
- Use professional but engaging language
- Include specific achievements with metrics where possible
- Show genuine enthusiasm without being overly casual
- Tailor content to the specific role and company
- Avoid generic phrases and clichés
- Use active voice and strong action verbs

Format the output as clean markdown with proper formatting.
Use [Your Name], [Your Email], [Your Phone] as placeholders for personal details.

IMPORTANT: At the end of the cover letter, include a small footer that says:
"Generated by: Revven Team | ${formattedDate}"

Do NOT use any other team name or date.`;

    const userPrompt = `Create a professional cover letter based on these details: "${topic}"
${jobTitle ? `Job Title/Position: ${jobTitle}` : ''}
${companyName ? `Company/Organization: ${companyName}` : ''}

Please generate a compelling, personalized cover letter that would impress hiring managers. Make it professional, specific, and engaging while maintaining appropriate length for a cover letter.`;

    console.log('Calling OpenRouter API for cover letter text...');
    
    const textResponse = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
        'Content-Type': 'application/json',
        'HTTP-Referer': 'https://revvenapp.lovable.app',
        'X-Title': 'Revven Cover Letter Generator',
      },
      body: JSON.stringify({
        model: 'openai/gpt-4.1',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        max_tokens: 2048,
        temperature: 0.7,
      }),
    });

    if (!textResponse.ok) {
      const errorText = await textResponse.text();
      console.error('OpenRouter API error:', textResponse.status, errorText);
      
      if (textResponse.status === 429) {
        return new Response(JSON.stringify({ error: 'Rate limit exceeded. Please try again later.' }), {
          status: 429,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
      throw new Error(`OpenRouter API error: ${textResponse.status}`);
    }

    const textData = await textResponse.json();
    const coverLetterContent = textData.choices?.[0]?.message?.content || '';

    if (!coverLetterContent) {
      throw new Error('No cover letter content generated');
    }

    console.log('Cover letter text generated successfully. Length:', coverLetterContent.length);

    return new Response(JSON.stringify({ 
      content: coverLetterContent,
      title: `Cover Letter: ${jobTitle || topic.substring(0, 50)}`,
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error generating cover letter:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    return new Response(JSON.stringify({ error: errorMessage }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
