import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import RevvenLogo from '@/components/RevvenLogo';

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-background">
      <header className="w-full px-6 py-4 flex items-center gap-4 border-b border-border">
        <Link to="/" className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="w-4 h-4" />
          <span className="text-sm">Back</span>
        </Link>
        <div className="flex items-center gap-2.5">
          <RevvenLogo />
          <span className="text-lg font-bold text-foreground tracking-tight">REVVEN</span>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold text-foreground mb-8">Terms of Service</h1>
        
        <div className="prose prose-slate max-w-none space-y-6 text-muted-foreground">
          <p className="text-sm text-muted-foreground">Last updated: January 7, 2026</p>
          
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">1. Acceptance of Terms</h2>
            <p>By accessing or using REVVEN ("Service," "Platform," "we," "us," or "our"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to all of these Terms, do not use or access the Service. These Terms constitute a legally binding agreement between you and REVVEN.</p>
            <p>We reserve the right to modify these Terms at any time. Continued use of the Service after changes constitutes acceptance of the modified Terms. We will notify users of material changes via email or in-app notification.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">2. Description of Service</h2>
            <p>REVVEN is an AI-powered content creation platform that enables users to generate, edit, and manage various types of digital content including but not limited to: images, videos, audio, voiceovers, social media posts, blog articles, newsletters, ebooks, and other marketing materials using artificial intelligence technologies.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">3. Account Registration and Security</h2>
            <p>To access certain features of the Service, you must create an account. You agree to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Provide accurate, current, and complete information during registration</li>
              <li>Maintain and promptly update your account information</li>
              <li>Maintain the security and confidentiality of your login credentials</li>
              <li>Accept responsibility for all activities that occur under your account</li>
              <li>Notify us immediately of any unauthorized use of your account</li>
            </ul>
            <p>You must be at least 18 years of age or the age of legal majority in your jurisdiction to use the Service. Access may require a valid invite code during beta periods.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">4. User-Generated Content and AI-Generated Content</h2>
            <p><strong>Your Content:</strong> You retain ownership of any content you upload, submit, or create using the Service ("User Content"). By using the Service, you grant REVVEN a worldwide, non-exclusive, royalty-free license to use, reproduce, modify, and display your User Content solely for the purpose of operating and improving the Service.</p>
            <p><strong>AI-Generated Content:</strong> Content generated by our AI tools ("Generated Content") is provided for your use subject to these Terms. You are granted a license to use Generated Content for personal and commercial purposes, subject to the following conditions:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>You are responsible for ensuring Generated Content does not infringe third-party rights</li>
              <li>Generated Content may not be used to create misleading deepfakes or impersonate real individuals without consent</li>
              <li>We do not guarantee exclusivity of Generated Content</li>
              <li>Similar outputs may be generated for other users based on similar prompts</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">5. Acceptable Use Policy</h2>
            <p>You agree NOT to use the Service to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Generate illegal, harmful, threatening, abusive, harassing, defamatory, or obscene content</li>
              <li>Create content depicting minors in inappropriate situations</li>
              <li>Generate content that promotes violence, discrimination, or hate speech</li>
              <li>Create deepfakes or synthetic media intended to deceive or defraud</li>
              <li>Impersonate individuals without their explicit consent</li>
              <li>Infringe on intellectual property rights, trademarks, or copyrights</li>
              <li>Distribute malware, spam, or engage in phishing activities</li>
              <li>Attempt to reverse-engineer, decompile, or extract source code from the Service</li>
              <li>Circumvent usage limits, security measures, or access controls</li>
              <li>Use automated systems or bots to access the Service without authorization</li>
              <li>Resell or redistribute the Service without written permission</li>
            </ul>
            <p>Violation of this policy may result in immediate account termination without refund.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">6. Intellectual Property Rights</h2>
            <p>The Service, including its original content, features, and functionality (excluding User Content and Generated Content), is owned by REVVEN and is protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.</p>
            <p>Our trademarks, logos, and service marks may not be used without prior written consent. Third-party AI models, libraries, and technologies integrated into our Service remain the property of their respective owners.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">7. Subscription and Payments</h2>
            <p>Certain features require a paid subscription. By subscribing, you agree to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Pay all applicable fees as described at the time of purchase</li>
              <li>Automatic renewal of subscriptions unless cancelled before the renewal date</li>
              <li>Provide accurate and complete billing information</li>
            </ul>
            <p><strong>Refund Policy:</strong> Subscription fees are generally non-refundable. Exceptions may be made at our sole discretion for service issues or extenuating circumstances. Contact support within 7 days of billing for refund requests.</p>
            <p><strong>Credits:</strong> Usage credits included in your plan expire at the end of each billing period and do not roll over. Additional credits purchased separately may have different expiration terms.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">8. Third-Party Services and APIs</h2>
            <p>The Service integrates with third-party AI providers, cloud services, and APIs. Your use of these integrations may be subject to additional terms and conditions. We are not responsible for the availability, accuracy, or content of third-party services.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">9. Disclaimer of Warranties</h2>
            <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ACCURACY.</p>
            <p>We do not warrant that:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>The Service will be uninterrupted, secure, or error-free</li>
              <li>AI-generated outputs will be accurate, complete, or suitable for your purposes</li>
              <li>Defects will be corrected in a timely manner</li>
              <li>The Service will meet your specific requirements</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">10. Limitation of Liability</h2>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, REVVEN AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE.</p>
            <p>IN NO EVENT SHALL OUR TOTAL LIABILITY EXCEED THE AMOUNT YOU PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR $100 USD, WHICHEVER IS GREATER.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">11. Indemnification</h2>
            <p>You agree to indemnify, defend, and hold harmless REVVEN and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable attorneys' fees) arising out of or related to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Your use of the Service</li>
              <li>Your User Content or use of Generated Content</li>
              <li>Your violation of these Terms</li>
              <li>Your violation of any third-party rights</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">12. Termination</h2>
            <p>We may terminate or suspend your account and access to the Service immediately, without prior notice or liability, for any reason, including breach of these Terms. Upon termination:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Your right to use the Service will cease immediately</li>
              <li>You may request a copy of your User Content within 30 days</li>
              <li>We may delete your data after a reasonable retention period</li>
              <li>Provisions that by their nature should survive termination shall survive</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">13. Governing Law and Dispute Resolution</h2>
            <p>These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to conflict of law principles.</p>
            <p>Any disputes arising from these Terms or the Service shall first be attempted to be resolved through good-faith negotiation. If unresolved within 30 days, disputes shall be settled by binding arbitration in accordance with the rules of the American Arbitration Association.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">14. Severability</h2>
            <p>If any provision of these Terms is found to be unenforceable or invalid, that provision shall be modified to the minimum extent necessary to make it enforceable, or if modification is not possible, severed from these Terms. The remaining provisions shall continue in full force and effect.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">15. Entire Agreement</h2>
            <p>These Terms, together with our Privacy Policy and any additional terms for specific features, constitute the entire agreement between you and REVVEN regarding the Service and supersede all prior agreements and understandings.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">16. Contact Information</h2>
            <p>For questions about these Terms of Service, please contact us at:</p>
            <p>Email: legal@revven.ai</p>
          </section>
        </div>
      </main>
    </div>
  );
};

export default TermsOfService;
